name       : libcdio-paranoia
version    : 10.2.2.0.1
release    : 6
source     :
    - https://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+2.0.1.tar.gz : 28d7d00e4a83d0221acda0fd2eb3e3240bf094db4c00a85998922201939fa952
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : CD paranoia libraries from libcdi
description: |
    CD paranoia libraries from libcdi
builddeps  :
    - pkgconfig(libcdio)
setup      : |
    %configure --disable-static \
               --disable-example-progs \
               --enable-cpp-progs
build      : |
    %make
install    : |
    %make_install
    ln -s cd-paranoia $installdir/usr/bin/cdparanoia
check      : |
    %make check
