name       : libcdio-paranoia
version    : 10.2.0.94.2
release    : 5
source     :
    - https://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+0.94+2.tar.gz : d60f82ece97eeb92407a9ee03f3499c8983206672c28ae5e4e22179063c81941
license    : LGPL-2.1
component  : multimedia.library
summary    : CD paranoia libraries from libcdi
description: |
    CD paranoia libraries from libcdi
builddeps  :
    - pkgconfig(libcdio)
setup      : |
    %configure --disable-static \
               --disable-example-progs \
               --enable-cpp-progs
build      : |
    %make
install    : |
    %make_install
    ln -s cd-paranoia $installdir/usr/bin/cdparanoia
check      : |
    %make check
