name       : libcdio-paranoia
version    : 10.2.0.93.1
release    : 1
source     :
    - http://ftp.gnu.org/gnu/libcdio/libcdio-paranoia-10.2+0.93+1.tar.gz : 4617792b4eb301de45b61732bdc0617447ad06b53068ae45db37695275c0dd4c
license    : LGPL-2.1
summary    : CD paranoia libraries from libcdi
description: |
    CD paranoia libraries from libcdi
builddeps  :
    - pkgconfig(libcdio)
setup      : |
    %configure --disable-static \
               --disable-example-progs \
               --enable-cpp-progs
build      : |
    %make
install    : |
    %make_install
